print("My name is Spencer")
print("I like to play a lot of sports, like basketball, soccer, and baseball, as well as golf")
print("My favorite is basketball, though")
print()
print("Recently, I've also enjoyed cooking")
print()
name = input("What's your name?")
print() 
print(f"Hi {name}, what's up?")
input()